account/urls.py
from django.urls import path
from . import views
import account.consumers as consumers

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/success/', views.signupSuccess, name='SUsuccess'),
    path('cancel_subscription/', views.cancel_subscription, name='cancel_subscription'),
    path('get_chat_history/<str:username>/', views.get_chat_history, name='get_chat_history'),
    path('<str:username>/editProfile/', views.edit_profile, name='editProfile'),
    path('<str:username>/', views.view_profile, name='view_profile'),
]

websocket_urlpatterns = [
    path("ws/chat/<str:username>/", consumers.ChatConsumer.as_asgi()),  # Conexión WebSocket
]

nextdoordeals/urls.py
from django.contrib import admin
from django.urls import path, include
from property.views import error
from account.views import logout_logic, loginUser, show_appointments, send_message, subscription, create_checkout_session, success, fail
from django.conf.urls.static import static
from django.conf import settings
from account import consumers
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('property.urls')),
    path('error/', error, name='error'),
    path('logout/', logout_logic, name = 'logout'),
    path('login/', loginUser, name = 'login'),
    path('appointments/', show_appointments, name = 'appointments'),
    path('send_message/', send_message, name='send_message'),
    path('subscription/', subscription, name = 'info_subscription'),
    path('create-checkout-session/', create_checkout_session, name = 'pay'),
    path('checkout_success/', success, name = 'pay_success'),
    path('checkout_fail/', fail, name = 'pay_fail')
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

websocket_urlpatterns = [
    path('ws/chat/<str:room_name>/', consumers.ChatConsumer.as_asgi()),
]

property/urls.py
from django.urls import path
from .views import home, publish, view_property, schedule_appointment, favourite, add_review, editProperty
urlpatterns = [path('', home, name = 'home'), 
               path('publish/', publish, name = 'publish'),
                path('<int:id>/', view_property, name = 'property_info'),
                path('<int:id>/appointment/', schedule_appointment, name = "appointment"),
                path('<int:id>/editProperty', editProperty, name = 'editProperty'),
                ]

property/models.py
from django.db import models
from account.models import Account


    
class City(models.Model):
    name = models.CharField(max_length = 50)
    
class District(models.Model):
    name = models.CharField(max_length = 50)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    
class PropertyType(models.Model):
    name = models.CharField(max_length = 50)

class Coordinates(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()

class Location(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    coordinates = models.ForeignKey(Coordinates, on_delete=models.CASCADE)

class Property(models.Model):
    title = models.CharField(max_length = 50)   
    description = models.CharField(max_length = 1000) 
    propertyType = models.ForeignKey(PropertyType, on_delete = models.CASCADE)
    price = models.IntegerField()
    SES = models.CharField(max_length = 1)
    associatedAccount = models.ForeignKey(Account, on_delete = models.CASCADE, related_name='propertys')
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True)

class Images(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name="imagenes")
    image = models.ImageField(null = True, blank = True, upload_to= "property/images/")

class Favourites(models.Model):
    associatedAccount = models.ForeignKey(Account, on_delete = models.CASCADE, related_name= 'favouriteAccs')
    property = models.ForeignKey(Property, on_delete = models.CASCADE)
    class Meta:
        unique_together = ('associatedAccount', 'property') 

class AppointmentStatus(models.Model):
    name = models.CharField(max_length=30, blank = False, null = False)

class Appointment(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name = 'appointments')
    requester = models.ForeignKey(Account, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.ForeignKey(AppointmentStatus, on_delete = models.CASCADE, default=3)

class Visit(models.Model):
    visited_user = models.ForeignKey(Account, on_delete = models.CASCADE, related_name='visits')
    date = models.DateTimeField(auto_now_add=True)

class Review(models.Model):
    reviewer = models.ForeignKey(Account, on_delete=models.CASCADE)
    reviewed_property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='reviews')
    comment = models.CharField(max_length=280, blank=True, null=True)
    rating = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

property/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Property, City, District, Images, PropertyType, Favourites, Location, Coordinates, Visit, Review, Appointment, AppointmentStatus
from .forms import PublishForm, DateForm, EditPropertyForm
from account.views import checkSession
from django.contrib import messages
import os
# Create your views here.

def filterPrice(minAttr, maxAttr, property):
    if minAttr:
        minAttr = float(minAttr)
        property = property.filter(price__gte = minAttr)
    if maxAttr:
        maxAttr = float(maxAttr)
        if minAttr and minAttr <= maxAttr:
            property = property.filter(price__lte = maxAttr)
        elif not minAttr:
            property = property.filter(price__lte = maxAttr)
    return property

def filterSES(minAttr, maxAttr, property):
    if minAttr:
        minAttr = int(minAttr)
        property = property.filter(SES__gte = minAttr)

    if maxAttr:
        maxAttr = int(maxAttr)
        if minAttr and minAttr <= maxAttr:
            property = property.filter(SES__lte = maxAttr)
        elif not minAttr:
            property = property.filter(SES__lte = maxAttr)
    return property

def filterDistrict(district, properties):
    return properties.filter(location__district = district)
    

def home(request):
    searchTerm = request.GET.get('searchProperty')
    minPrice = request.GET.get('minPrice')
    maxPrice = request.GET.get('maxPrice')
    minSES = request.GET.get('minSES')
    maxSES = request.GET.get('maxSES')
    district = request.GET.get('district')

    isChecked = request.GET.get('useRangeSES') == 'on'  
    singleSES = request.GET.get('singleSES') 
    highlighted_properties = Property.objects.filter(
    associatedAccount__subscription__is_active=True).distinct()
    normal_properties = Property.objects.exclude(id__in=highlighted_properties.values_list('id', flat=True))
 
    highlighted_properties = filterPrice(minPrice, maxPrice, highlighted_properties)
    normal_properties = filterPrice(minPrice, maxPrice, normal_properties)
    if not isChecked:
        minSES = singleSES
        maxSES = singleSES
    highlighted_properties = filterSES(minSES, maxSES, highlighted_properties) 
    normal_properties = filterSES(minSES, maxSES, normal_properties) 
    districts = District.objects.all()

    if searchTerm: 
        highlighted_properties = highlighted_properties.filter(title__icontains=searchTerm)
        normal_properties = highlighted_properties.filter(title__icontains=searchTerm)
    else:
        searchTerm = None

    if district:
        highlighted_properties = filterDistrict(district, highlighted_properties)
        normal_properties = filterDistrict(district, normal_properties)
        

    sessionActive = checkSession(request.user)

    if sessionActive and request.GET.get("favourite"):  # Si el usuario está autenticado y activó el filtro
        account = request.user.account
        favourite_properties = Favourites.objects.filter(associatedAccount=account).values_list('property', flat=True)
        highlighted_properties = highlighted_properties.filter(id__in=favourite_properties)  # Filtra solo las propiedades favoritas
        normal_properties = normal_properties.filter(id__in=favourite_properties)
    propertyPresence = len(highlighted_properties) + len(normal_properties) > 0

    return render(request, 'home.html', {
        'searchTerm': searchTerm,
        'h_properties': highlighted_properties,
        'n_properties': normal_properties,
        'minPrice': minPrice,
        'maxPrice': maxPrice,
        'propertyPresence': propertyPresence,
        'districts': districts, 'types': PropertyType.objects.all(),
    })


def publish(request):
    if request.method == "POST":
        publishForm = PublishForm(request.POST, request.FILES)
        if publishForm.is_valid():
            data = publishForm.cleaned_data
            title = data["title"]
            type = data["type"]
            description = data["description"]
            SES = data["SES"]
            district = data["district"]
            location = data["location"]
            coordinates = Coordinates.objects.create(latitude = location.y, longitude = location.x)
            location = Location(district = District.objects.get(id = int(district) - 1), coordinates = coordinates)
            location.save()
            price = data["price"]
            newProperty = Property(associatedAccount = request.user.account, title = title, description = description, SES = str(int(SES) - 1), price = price, propertyType = PropertyType.objects.get(id = int(type)-1), location = location)
            newProperty.save()
            images = data["pictures"]
            for i in images:
                Images.objects.create(property = newProperty, image = i)
            
            publishForm = PublishForm()
            messages.success(request, "Property published succesfully")
    else:
        publishForm = PublishForm()
        
        is_premium = True
        if request.user.is_authenticated:
            try:
                is_premium = request.user.account.subscription.is_active
            except:
                pass

    return render(request, 'publish.html', {'publishForm':publishForm})

def get_disabled_dates(property):
    appointments = property.appointments.filter(status__name = 'Approved')
    disabled_dates = []
    for appointment in appointments:
        disabled_dates.append(appointment.date)
    if len(disabled_dates) > 0:
        return disabled_dates
    else:
        return None

def request_appointment(property, date, account):
    Appointment.objects.create(property = property, requester = account, date = date)



def view_property(request, id):
    property = Property.objects.get(id = id)
    type = property.propertyType.name
    sessionActive = checkSession(request.user)
    if sessionActive and request.user != property.associatedAccount:
        disabled_dates = get_disabled_dates(property)
        needs_date_form = True
    else:
        disabled_dates = None
        needs_date_form = False
    
    if needs_date_form:
        date_form = DateForm(disabled_dates=disabled_dates)
    else:
        date_form = None

    Visit.objects.create(visited_user = property.associatedAccount)

    if sessionActive:
        is_fav = len(Favourites.objects.filter(property = property, associatedAccount = request.user.account)) != 0
    else:
        is_fav = None


    if request.POST:
        action = request.POST.get('action')
        if action == 'favourite':
            favourite(request, id)
        elif action == 'review':
            add_review(request, id)
        elif len(Appointment.objects.filter(property = property, date = request.POST.get('date'))) == 0:
            request_appointment(property, request.POST.get('date'), request.user.account)
        return redirect('property_info', id = id)
    else:
        return render(request, 'property_info.html', {'property':property, 'pType': type, 'is_fav': is_fav, 'date_form':date_form, 'api_key':os.getenv('maps_api')})
    try:
        ...
    except:
        return redirect('error')


#EDITAR LA PROPERTY 
def editProperty(request, id):
    property = Property.objects.get(id=id)
    sessionActive = checkSession(request.user)

    # Verificamos que la sesión esté activa y que el usuario sea el dueño
    if sessionActive and request.user != property.associatedAccount:

        if request.method == 'POST':
            form = EditPropertyForm(request.POST, request.FILES)
            if form.is_valid():
                # Actualizamos los campos de la propiedad
                property.title = form.cleaned_data['title']
                property.description = form.cleaned_data['description']
                property.propertyType = PropertyType.objects.get(id=form.cleaned_data['propertyType'])
                property.SES = form.cleaned_data['SES']
                property.price = form.cleaned_data['price']

                # Se actualiza la localización si es necesario
                district = District.objects.get(id=form.cleaned_data['location'])
                location = property.location
                location.district = district
                location.save()

                property.save()

                # Guardar las nuevas imágenes si se suben
                for image in form.cleaned_data['image']:
                    Images.objects.create(property=property, image=image)

                return redirect('property_info', id=property.id)  # o donde muestres la propiedad
        else:
            # Cargar datos iniciales del formulario
            initial_data = {
                'title': property.title,
                'description': property.description,
                'propertyType': property.propertyType.id,
                'SES': property.SES,
                'location': property.location.district.id,
                'price': property.price,
            }
            form = EditPropertyForm(initial=initial_data)
    else:

        return redirect('home')  # o alguna otra vista a la que quieras redirigir

    context = {
        'form': form,
        'property': property,
    }

    return render(request, 'editProperty.html', context)


def favourite(request, id):
    account = request.user.account
    property = Property.objects.get(id = id)
    try:
        favourites = Favourites.objects.get(associatedAccount = account, property = property)
        favourites.delete()
    except:
        Favourites.objects.create(associatedAccount = account, property = property)
        
    
    return redirect('property_info', id = id)

def schedule_appointment(request, id):
    ...

def error(request):
    return render(request, 'error.html')

def add_review(request, id):
    account = request.user.account
    property = Property.objects.get(id = id)
    if request.POST:
        rating = request.POST.get('rating')

property/templates/editProperty.html
{% extends 'base.html' %}

{% block title %}
<title>NextDoorDeals | Edit Property</title>
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h2>Edit Property</h2>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="row mb-4">
        <div class="col-md-6">
          <label for="id_title" class="form-label">Property Title:</label>
          {{ form.title }}
          {% if form.title.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.title.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="col-md-6">
          <label for="id_price" class="form-label">Price:</label>
          {{ form.price }}
          {% if form.price.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.price.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-md-6">
          <label for="id_description" class="form-label">Description:</label>
          {{ form.description }}
          {% if form.description.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.description.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="col-md-6">
          <label for="id_propertyType" class="form-label">Property Type:</label>
          {{ form.propertyType }}
          {% if form.propertyType.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.propertyType.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-md-6">
          <label for="id_SES" class="form-label">SES:</label>
          {{ form.SES }}
          {% if form.SES.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.SES.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="col-md-6">
          <label for="id_location" class="form-label">District:</label>
          {{ form.location }}
          {% if form.location.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.location.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-md-12">
            <br>
          <label for="id_image" class="form-label">Update Property Images:</label>
          {{ form.image }}
          {% if form.image.errors %}
            <div class="alert alert-danger mt-2">
              {% for error in form.image.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-md-12 text-center">
          <button type="submit" class="btn text-white btn-lg" style="background-color: #11324f; border-color: #11324f;">
            Save Changes
          </button>
          
        </div>
      </div>
    </form>

    <h3 class="mt-4">Current Property Images:</h3>
    <div class="row">
      {% for image in property.imagenes.all %}
        <div class="col-md-3 mb-3">
          <img src="{{ image.image.url }}" alt="Property Image" class="img-fluid rounded">
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

property/templates/publish.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>NextDoorDeals | Publish Property</title>
    <meta name="description" content="Publish your property listing on NextDoorDeals">
{% endblock %}

{% block extra_css %}
        /* Modern CSS Variables for easy theming */
        :root {
            --primary-gradient-start: #0a3d62;
            --primary-gradient-end: #1e5799;
            --primary-color: #0a3d62;
            --secondary-color: #2b3499;
            --border-radius: 1rem;
            --transition-speed: 0.3s;
        }

        .card {
            border-radius: var(--border-radius);
            transition: transform var(--transition-speed) ease;
        }

        .card:hover {
            transform: translateY(-2px);
        }

        .bg-gradient-primary {
            background: linear-gradient(135deg, var(--primary-gradient-start) 0%, var(--primary-gradient-end) 100%);
            border-radius: var(--border-radius) var(--border-radius) 0 0;
        }

        .btn-gradient-primary {
            background: linear-gradient(45deg, var(--primary-gradient-start), var(--primary-gradient-end));
            color: white;
            border: none;
            border-radius: 0.5rem;
            padding: 1rem 2rem;
            font-weight: 600;
            transition: all var(--transition-speed) ease;
        }

        .btn-gradient-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 15px rgba(10, 61, 98, 0.3);
        }

        .btn-gradient-primary:focus {
            outline: none;
            box-shadow: 0 0 0 3px rgba(10, 61, 98, 0.3);
        }

        .custom-file-upload {
            position: relative;
            margin-top: 1rem;
        }

        .custom-file-upload .form-control {
            padding: 2rem;
            border: 2px dashed #dee2e6;
            border-radius: 1rem;
            background-color: #f8fafc;
            transition: all var(--transition-speed) ease;
        }

        .custom-file-upload .form-control:hover,
        .custom-file-upload .form-control:focus {
            border-color: var(--primary-color);
            background-color: #ffffff;
        }

        .form-group label {
            font-weight: 600;
            color: var(--secondary-color);
            margin-bottom: 0.5rem;
        }

        .form-control:focus {
            border-color: var(--secondary-color);
            box-shadow: 0 0 0 3px rgba(43, 52, 153, 0.15);
        }

        .alert {
            border: none;
            border-radius: var(--border-radius);
        }

        .alert-success {
            background-color: #d1fae5;
            color: #065f46;
        }

        .alert-error {
            background-color: #fee2e2;
            color: #991b1b;
        }

        /* Accessibility improvements */
        .form-control:focus-visible {
            outline: 2px solid var(--primary-color);
            outline-offset: 2px;
        }

        /* Loading state */
        .btn-gradient-primary.loading {
            position: relative;
            pointer-events: none;
            opacity: 0.8;
        }

        .btn-gradient-primary.loading::after {
            content: "";
            position: absolute;
            width: 1.25rem;
            height: 1.25rem;
            top: 50%;
            left: 50%;
            margin: -0.625rem 0 0 -0.625rem;
            border: 2px solid white;
            border-top-color: transparent;
            border-radius: 50%;
            animation: button-loading-spinner 1s ease infinite;
        }

        @keyframes button-loading-spinner {
            from {
                transform: rotate(0turn);
            }
            to {
                transform: rotate(1turn);
            }
        }
        .geo-icon-custom {
        color: #11324F;
    }
{% endblock %}

{% block content %}
    <div class="container py-5">
        {% if messages %}
        <div class="messages mb-4" role="alert" aria-live="polite">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <div class="d-flex align-items-center">
                        {% if message.tags == 'success' %}
                            <i class="bi bi-check-circle-fill me-2" aria-hidden="true"></i>
                        {% else %}
                            <i class="bi bi-exclamation-triangle-fill me-2" aria-hidden="true"></i>
                        {% endif %}
                        <div>{{ message }}</div>
                        <button type="button" 
                                class="btn-close ms-auto" 
                                data-bs-dismiss="alert" 
                                aria-label="Close">
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        
        <div class="card border-0 shadow-lg mx-auto" style="max-width: 800px;">
            <div class="card-header bg-gradient-primary text-white py-4">
                <div class="d-flex align-items-center justify-content-center">
                    <i class="bi bi-house-add fs-1 me-3" aria-hidden="true"></i>
                    <h1 class="h2 mb-0">Publish New Property</h1>
                </div>
            </div>
            
            <div class="card-body p-4 p-md-5">
                <form method="post" enctype="multipart/form-data" id="publishForm">
                    {% csrf_token %}
                    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"></script>
                    {{ publishForm.media }}
                    <div class="row g-4">
                        <!-- Información básica -->
                        <div class="col-12">
                            <div class="section-header d-flex align-items-center mb-3">
                                <i class="bi bi-info-circle text-primary me-2" aria-hidden="true"></i>
                                <h2 class="h4 text-primary mb-0">Basic Information</h2>
                            </div>
                            {{ publishForm.title|as_crispy_field }}
                        </div>
                        <div class="col-12">
                            {{ publishForm.description|as_crispy_field }}
                        </div>
                        
                        <div class="col-md-6">
                            {{ publishForm.SES|as_crispy_field }}
                        </div>
            
                        <div class="col-md-6">
                            {{ publishForm.type|as_crispy_field }}
                        </div>
            
                        <div class="col-md-6">
                            {{ publishForm.price|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ publishForm.district|as_crispy_field }}
                        </div>
            
                        <!-- Ubicación: Google Maps -->
                        <div class="col-12">
                            <div class="section-header d-flex align-items-center mb-3 mt-4">
                                <i class="bi bi-geo-alt text-primary me-2" aria-hidden="true"></i>
                                <h2 class="h4 text-primary mb-0">Property Location</h2>
                            </div>
                            <div class="custom-map-container">
                                <!-- Aquí está el widget de Google Maps para seleccionar ubicación -->
                                {{ publishForm.location }}
                            </div>
                        </div>
            
                        <!-- Media Upload -->
                        <div class="col-12">
                            <div class="section-header d-flex align-items-center mb-3 mt-4">
                                <i class="bi bi-images text-primary me-2" aria-hidden="true"></i>
                                <h2 class="h4 text-primary mb-0">Media Upload</h2>
                            </div>
                            <div class="custom-file-upload">
                                {{ publishForm.pictures|as_crispy_field }}
                                <small class="text-muted d-block mt-2">
                                    Supported formats: JPG, PNG, WEBP (Max size: 5MB per image)
                                </small>
                            </div>
                        </div>
                    </div>

                    <div class="d-grid mt-5">
                        <button type="submit" 
                                class="btn btn-gradient-primary"
                                id="submitButton">
                            <i class="bi bi-upload me-2" aria-hidden="true"></i>
                            Publish Property
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}